# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  
  desc "Cleans and builds the PROJECTNAME scheme in Debug configuration"
  lane :clean_and_build do |options|
      xcodebuild(
        project: "PROJECTNAME.xcodeproj",
        scheme: "PROJECTNAME",
        configuration: "Debug",
        clean: true,
        build: true,
        destination: "generic/platform=iOS",
        build_settings: {
          "CODE_SIGNING_ALLOWED" => "NO",
          "CODE_SIGN_IDENTITY" => ""
        },
        buildlog_path: options[:buildlog_path]
      )
  end
  
end
